<?php

namespace App\Support;

/**
 * Maps team/country names to ISO codes used by the flag-icons library
 * (lowercase ISO 3166-1 alpha-2, plus gb-eng/gb-sct/gb-wls subdivisions).
 */
class CountryFlags
{
    /** @var array<string, string> */
    private const MAP = [
        // English names
        'mexico' => 'mx',
        'south africa' => 'za',
        'south korea' => 'kr',
        'korea republic' => 'kr',
        'czechia' => 'cz',
        'czech republic' => 'cz',
        'canada' => 'ca',
        'bosnia and herzegovina' => 'ba',
        'bosnia' => 'ba',
        'qatar' => 'qa',
        'switzerland' => 'ch',
        'brazil' => 'br',
        'morocco' => 'ma',
        'haiti' => 'ht',
        'scotland' => 'gb-sct',
        'united states' => 'us',
        'united states of america' => 'us',
        'usa' => 'us',
        'paraguay' => 'py',
        'australia' => 'au',
        "t\xc3\xbcrkiye" => 'tr',
        'turkiye' => 'tr',
        'turkey' => 'tr',
        'germany' => 'de',
        'curacao' => 'cw',
        'ivory coast' => 'ci',
        "cote d'ivoire" => 'ci',
        'ecuador' => 'ec',
        'netherlands' => 'nl',
        'japan' => 'jp',
        'sweden' => 'se',
        'tunisia' => 'tn',
        'belgium' => 'be',
        'egypt' => 'eg',
        'iran' => 'ir',
        'new zealand' => 'nz',
        'spain' => 'es',
        'cabo verde' => 'cv',
        'cape verde' => 'cv',
        'saudi arabia' => 'sa',
        'uruguay' => 'uy',
        'france' => 'fr',
        'iraq' => 'iq',
        'norway' => 'no',
        'senegal' => 'sn',
        'argentina' => 'ar',
        'algeria' => 'dz',
        'austria' => 'at',
        'jordan' => 'jo',
        'portugal' => 'pt',
        'dr congo' => 'cd',
        'democratic republic of the congo' => 'cd',
        'uzbekistan' => 'uz',
        'colombia' => 'co',
        'croatia' => 'hr',
        'england' => 'gb-eng',
        'ghana' => 'gh',
        'panama' => 'pa',
        'wales' => 'gb-wls',
        'denmark' => 'dk',
        'poland' => 'pl',
        'serbia' => 'rs',
        'cameroon' => 'cm',
        'costa rica' => 'cr',
        'bolivia' => 'bo',
        'venezuela' => 've',
        'chile' => 'cl',
        'peru' => 'pe',
        'honduras' => 'hn',
        'guatemala' => 'gt',
        'el salvador' => 'sv',
        'jamaica' => 'jm',
        'nigeria' => 'ng',
        'ukraine' => 'ua',
        'romania' => 'ro',
        'hungary' => 'hu',
        'slovakia' => 'sk',
        'slovenia' => 'si',
        'finland' => 'fi',
        'iceland' => 'is',
        'ireland' => 'ie',
        'greece' => 'gr',
        'albania' => 'al',
        'north macedonia' => 'mk',
        'macedonia' => 'mk',
        'montenegro' => 'me',
        'latvia' => 'lv',
        'lithuania' => 'lt',
        'estonia' => 'ee',
        'georgia' => 'ge',
        'armenia' => 'am',
        'azerbaijan' => 'az',
        'kazakhstan' => 'kz',
        'china' => 'cn',
        'thailand' => 'th',
        'indonesia' => 'id',
        'india' => 'in',
        'uae' => 'ae',
        'united arab emirates' => 'ae',
        'bahrain' => 'bh',
        'kuwait' => 'kw',
        'oman' => 'om',
        'kenya' => 'ke',
        'angola' => 'ao',
        'tanzania' => 'tz',
        'zambia' => 'zm',
        'zimbabwe' => 'zw',
        'mozambique' => 'mz',
        'italy' => 'it',
        'russia' => 'ru',
        'luxembourg' => 'lu',
        'trinidad and tobago' => 'tt',
        'cuba' => 'cu',
        'nicaragua' => 'ni',
        'north korea' => 'kp',
        'vietnam' => 'vn',
        'philippines' => 'ph',
        'pakistan' => 'pk',
        'bangladesh' => 'bd',
        'moldova' => 'md',
        'bulgaria' => 'bg',
        'kosovo' => 'xk',
        'syria' => 'sy',
        'libya' => 'ly',

        // Spanish names
        'espana' => 'es',
        "espa\xc3\xb1a" => 'es',
        'francia' => 'fr',
        'alemania' => 'de',
        'paises bajos' => 'nl',
        'holanda' => 'nl',
        'belgica' => 'be',
        'suiza' => 'ch',
        'suecia' => 'se',
        'noruega' => 'no',
        'dinamarca' => 'dk',
        'finlandia' => 'fi',
        'islandia' => 'is',
        'irlanda' => 'ie',
        'escocia' => 'gb-sct',
        'inglaterra' => 'gb-eng',
        'gales' => 'gb-wls',
        'italia' => 'it',
        'grecia' => 'gr',
        'croacia' => 'hr',
        'eslovenia' => 'si',
        'eslovaquia' => 'sk',
        'hungria' => 'hu',
        'rumania' => 'ro',
        'ucrania' => 'ua',
        'polonia' => 'pl',
        'macedonia del norte' => 'mk',
        'azerbaiyan' => 'az',
        'kazajistan' => 'kz',
        'brasil' => 'br',
        'estados unidos' => 'us',
        'marruecos' => 'ma',
        'argelia' => 'dz',
        'tunez' => 'tn',
        'egipto' => 'eg',
        'camerun' => 'cm',
        'costa de marfil' => 'ci',
        'sudafrica' => 'za',
        'corea del sur' => 'kr',
        'corea del norte' => 'kp',
        'japon' => 'jp',
        'arabia saudita' => 'sa',
        'irak' => 'iq',
        'jordania' => 'jo',
        'emiratos arabes unidos' => 'ae',
        'turquia' => 'tr',
        "turqu\xc3\xada" => 'tr',
        'nueva zelanda' => 'nz',
        'nueva zelandia' => 'nz',
        'republica checa' => 'cz',
        'bosnia y herzegovina' => 'ba',
        'republica democratica del congo' => 'cd',
        'letonia' => 'lv',
        'lituania' => 'lt',
        'trinidad y tobago' => 'tt',
        'curazao' => 'cw',
        'rusia' => 'ru',
        'siria' => 'sy',
        'libia' => 'ly',
        'azerbaiyan' => 'az',
        'filipinas' => 'ph',
        'tailandia' => 'th',
        'pakistan' => 'pk',
        'india' => 'in',
        'bahrain' => 'bh',
        'bahrein' => 'bh',
        'kuwait' => 'kw',
        'angola' => 'ao',

        // Portuguese names
        'alemanha' => 'de',
        'espanha' => 'es',
        'franca' => 'fr',
        'suica' => 'ch',
        'suecia' => 'se',
        'marrocos' => 'ma',
        'egito' => 'eg',
        'camaroes' => 'cm',
        'coreia do sul' => 'kr',
        'japao' => 'jp',
        'arabia saudita' => 'sa',
        'iraque' => 'iq',
        'nova zelandia' => 'nz',
        'croacia' => 'hr',
        'republica tcheca' => 'cz',
        'servia' => 'rs',
        'hungria' => 'hu',
        'ucrania' => 'ua',
        'argelia' => 'dz',
        'costa do marfim' => 'ci',
        'africa do sul' => 'za',
        'holanda' => 'nl',
        'belgica' => 'be',
        'finlandia' => 'fi',
        'dinamarca' => 'dk',
        'noruega' => 'no',
        'georgia' => 'ge',
    ];

    public static function codeFor(?string $name): ?string
    {
        if ($name === null) {
            return null;
        }

        return self::MAP[mb_strtolower(trim($name))] ?? null;
    }
}
